name: sherif_nxt_assessment
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  provider: ^6.0.2
  http: ^1.1.0
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  flutter_advanced_switch: ^3.1.0
  flutter_svg: ^2.0.0+1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_rating_bar: ^4.0.1
  ticket_widget: ^1.0.2
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.1
  connectivity_plus: ^4.0.0
  loader_overlay: ^2.0.6
  expandable_widgets: ^1.0.3+1
  cached_network_image: ^3.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf

